name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  bfhash-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build tests
        run: make -C bfhash_tests CC=${{ matrix.cc }}

      - name: Run tests
        run: make -C bfhash_tests run
